name: alvaro carril blog
markdown: kramdown
highlighter: pygments
encoding: utf-8
url: http://acarril.github.io
title: alvaro carril blog
permalink: /:year/:month/:title.html
relative_permalinks: true
baseurl: /
excerpt_separator: <span></span>

# Menu bar
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
