# Site settings
title: alvaro carril blog
url: http://acarril.github.io    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl:  # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  I'm an economist working at J-PAL LAC.

# Your information
email: acarril@fen.uchile.cl
author: Alvaro Carril
avatar: "https://avatars3.githubusercontent.com/u/9773292?v=3&s=460"
profile: Economist / Research analyst at J-PAL
twitter_username: alvcarril
github_username:  acarril
researchgate_username: Alvaro_Carril

# Comment Service
disqus_shortname: acarril   # get one: https://disqus.com/admin/signup/

permalink: /posts/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
