# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: pmarsceill/just-the-docs
title: Alvaro Carril
email: acarril@princeton.edu
description: >- # this means to ignore newlines until "baseurl:"
  I'm a PhD student at Princeton. I work with computers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acarril.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  acarril
favicon: /assets/icon/analytics-trans.png
# footer_content: "Copyright &copy; 2017-2019 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
# Aux links for the upper right navigation
aux_links:
    "Jump to Github repository >":
      - "//github.com/acarril"

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  projects:
    output: true
    permalink: /projects/:path/
  research:
    output: true
    permalink: /research/:title

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: research

# Includes
include: ["_pages"]

# Outputting
permalink: /posts/:title
category_dir: categories

# Build settings
markdown: kramdown
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
