title: Alvaro Carril
description: econ research &amp; computer stuff
show_downloads: false
google_analytics: UA-54241026-2

excerpt_separator: <!--more-->
permalink: /posts/:title

gems:
  - jekyll-feed