# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alvaro Carril
email: acarril@fen.uchile.cl
description: > # this means to ignore newlines until "baseurl:"
  Tools of the trade of the econ research analyst
baseurl:
url: http://acarril.github.io
permalink:          /posts/:title

twitter_username: alvcarril 
github_username:  acarril

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "resources"
    href:           "/resources"
  - name:           "posts"
    href:           "/posts"

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname: acarril

# used this for post_excerpt at index_page
# excerpt_separator: <!--description-->
