# Basic
name:               "Alvaro Carril"
title:              "econ blog"
description:        "tools of the trade of the econ research analyst"


# URL
url:                http://acarril.github.io
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /posts/:title

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "resources"
    href:           "/resources"
  - name:           "posts"
    href:           "/posts"

# Plugins
paginate: 5

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"
