title: "Alvaro Carril"
description: "econ research &amp; computer stuff"
show_downloads: true
google_analytics:
theme: 
markdown: kramdown
kramdown:  
  parse_block_html: true
encoding:         UTF-8
gems:
  - jekyll-feed

excerpt_separator: <!--more-->