name: acarril blog prueba8
markdown: kramdown
highlighter: pygments
encoding: utf-8
url: http://acarril.github.io
title: acarril econ blog
# tagline: econ blog
permalink: /:year/:month/:title.html
relative_permalinks: true

# Setup


paginate:            1
baseurl:             ""

# Menu bar
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:             0.9.0
github:
  repo:              https://github.com/acarril
