name: acarril blog
markdown: kramdown #redcarpet
highlighter: rouge #pygments
encoding: utf-8
url: http://acarril.github.io
excerpt_separator: <span></span>
permalink: /:year/:month/:title.html
baseurl: /
author: Alvaro Carril 
title: acarril blog
rss_name: blogfeed.xml
exclude: [mathstats.py]
disqus: false
